# Generated by Django 5.2.16 on 2026-07-16 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(max_length=200)),
                ('indirizzo', models.CharField(blank=True, max_length=255)),
                ('cap', models.CharField(blank=True, max_length=10)),
                ('citta', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=2)),
                ('piva', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['ragione_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Preventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Es. 1045_26', max_length=20)),
                ('revisione', models.CharField(blank=True, default='1.0', max_length=20)),
                ('data', models.DateField()),
                ('oggetto_titolo', models.CharField(blank=True, default='Offerta', max_length=200)),
                ('oggetto_righe', models.TextField(blank=True, help_text='Un punto elenco per riga.')),
                ('condizioni_fornitura', models.TextField(blank=True, default='Consegna inclusa\nIva esclusa\nPagamento Riba o BB a 30 GGDF', help_text='Un punto elenco per riga.')),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('inviato', 'Inviato'), ('accettato', 'Accettato'), ('rifiutato', 'Rifiutato')], default='bozza', max_length=20)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preventivi', to='preventivi.cliente')),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventivi_creati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='SezionePreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('preventivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sezioni', to='preventivi.preventivo')),
            ],
            options={
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VoceProventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('descrizione', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('specifiche', models.TextField(blank=True, help_text='Un punto elenco per riga.')),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='preventivi/voci/')),
                ('quantita', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unita_misura', models.CharField(blank=True, default='Cad', max_length=20)),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prezzo_scontato', models.DecimalField(blank=True, decimal_places=2, help_text='Se valorizzato, il prezzo unitario viene mostrato barrato nel PDF.', max_digits=10, null=True)),
                ('note', models.TextField(blank=True, help_text='Es. "a vostro carico", "manodopera a consuntivo 35€/h".')),
                ('escluso_da_totale', models.BooleanField(default=False, help_text='Voce descritta nel preventivo ma non conteggiata nel totale (es. a carico del cliente).')),
                ('sezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voci', to='preventivi.sezionepreventivo')),
            ],
            options={
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='preventivo',
            constraint=models.UniqueConstraint(fields=('numero', 'revisione'), name='unique_preventivo_numero_revisione'),
        ),
    ]
