# Generated by Django 5.2.16 on 2026-07-16 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventivi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('specifiche', models.TextField(blank=True, help_text='Un punto elenco per riga.')),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='preventivi/catalogo/')),
                ('unita_misura', models.CharField(blank=True, default='Cad', max_length=20)),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo di listino')),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['descrizione'],
            },
        ),
        migrations.AddField(
            model_name='voceproventivo',
            name='prodotto',
            field=models.ForeignKey(blank=True, help_text='Prodotto di catalogo da cui è stata prefillata questa voce (solo riferimento, non vincolante).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voci', to='preventivi.prodotto'),
        ),
    ]
