# Generated by Django 5.2.16 on 2026-07-17 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventivi', '0002_prodotto_voceproventivo_prodotto'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivo',
            name='cliente_id_portale',
            field=models.UUIDField(blank=True, help_text="Riferimento al cliente nell'anagrafica condivisa del Portale (clienti/api/internal/).", null=True),
        ),
        migrations.AlterField(
            model_name='preventivo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preventivi', to='preventivi.cliente'),
        ),
    ]
