# Generated by Django 5.2.16 on 2026-07-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventivi', '0004_cliente_condiviso_nel_portale'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivo',
            name='descrizione_interna',
            field=models.CharField(blank=True, help_text="Descrizione breve per identificare rapidamente il preventivo (es. 'WiFi sede Milano'). Non compare nel PDF.", max_length=200),
        ),
    ]
