# Generated by Django 5.2.16 on 2026-07-28 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventivi', '0005_preventivo_descrizione_interna'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProdotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ordine', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categorie prodotto',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='prodotto',
            options={'ordering': ['categoria__ordine', 'categoria__nome', 'descrizione']},
        ),
        migrations.AddField(
            model_name='prodotto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prodotti', to='preventivi.categoriaprodotto'),
        ),
    ]
