# Generated by Django 5.2.16 on 2026-07-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventivi', '0006_categoriaprodotto_alter_prodotto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivo',
            name='progetto',
            field=models.CharField(blank=True, help_text="Nome del progetto/commessa, usato per raggruppare i preventivi correlati nell'elenco.", max_length=200),
        ),
    ]
