# Generated by Django 5.2.16 on 2026-07-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventivi', '0007_preventivo_progetto'),
    ]

    operations = [
        migrations.AddField(
            model_name='voceproventivo',
            name='in_evidenza',
            field=models.BooleanField(default=False, help_text="Evidenzia la voce con uno sfondo tenue, sia nella scheda che nel PDF, per attirare l'attenzione del cliente."),
        ),
    ]
