# Generated by Django 5.2.16 on 2026-08-18 09:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventivi', '0008_voceproventivo_in_evidenza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='prezzo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prezzo di listino'),
        ),
        migrations.AlterField(
            model_name='voceproventivo',
            name='prezzo_scontato',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se valorizzato, il prezzo unitario viene mostrato barrato nel PDF.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='voceproventivo',
            name='prezzo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='voceproventivo',
            name='quantita',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
